version: '3'

services:
  web:
    image: rizalibnu/rzdashboard
    container_name: rzdashboard
    environment:
       VIRTUAL_HOST: rzdashboard.rizalibnu.com
       LETSENCRYPT_HOST: rzdashboard.rizalibnu.com
       LETSENCRYPT_EMAIL: hello@rizalibnu.com
    restart: always
    expose:
       - 80

networks:
  default:
    external:
      name: webproxy