version: '3'

services:
  web:
    image: rizalibnu/rz-dashboard
    container_name: rz-dashboard
    environment:
       VIRTUAL_HOST: rz-dashboard.rizalibnu.com
       LETSENCRYPT_HOST: rz-dashboard.rizalibnu.com
       LETSENCRYPT_EMAIL: hello@rizalibnu.com
    restart: always
    expose:
       - 80

networks:
  default:
    external:
      name: webproxy